A = input('Enter a name:')
B = input('Enter a name:')
C = input('Enter a name:')
D = input('Enter a name:')
E = input('Enter a name:')
F = input('Enter a name:')
G = input('Enter a name:')
H = input('Enter a name:')
I = input('Enter a name:')
J = input('Enter a name:')
K = input('Enter a name:')
L = input('Enter a name:')
M = input('Enter a name:')
N = input('Enter a name:')
O = input('Enter a name:')
P = input('Enter a name:')
Q = input('Enter a name:')
R = input('Enter a name:')
S = input('Enter a name:')
T = input('Enter a name:')
print(f'Here are the names that you listed: {A}')


print(B)
print(C)
print(D)
print(E)
print(F)
print(G)
print(H)
print(I)
print(J)
print(K)
print(L)
print(M)
print(N)
print(O)
print(P)
print(Q)
print(R)
print(S)
print(T)